# docker-compose.override.yml
version: '3.7'
services:
    php:
        volumes:
            - './apps/${SYMFONY_APP}/:/usr/src/app'

    nginx:
        volumes:
            - './apps/${SYMFONY_APP}/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
